name: andbeyondmedia
description: |
  abm-flutter is a robust Flutter package built on Google Ad Manager, designed to seamlessly integrate advanced ad functionalities into your applications. 
  This package not only simplifies the ad integration process but also enhances the user experience by providing additional features such as automatic ad refresh and efficient handling of unfilled ad spaces. 
  Perfect for developers looking to optimize their app's ad performance and revenue potential.
version: 0.0.1
homepage: http://hbadapt.andbeyond.media/Getting-Started-with-Android-SDK-Integration.html

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_mobile_ads: ^5.2.0
  visibility_detector: ^0.4.0+2
  http: ^1.2.2
  connectivity_plus: ^6.1.0
  path_provider: ^2.1.5
  package_info_plus: ^8.1.1
  collection: ^1.18.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
